/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Todos example
 * The TODO API description
 * OpenAPI spec version: 1.0
 */

export type authControllerRegisterResponse201 = {
  data: void;
  status: 201;
};

export type authControllerRegisterResponseSuccess =
  authControllerRegisterResponse201 & {
    headers: Headers;
  };
export type authControllerRegisterResponse =
  authControllerRegisterResponseSuccess;

export const getAuthControllerRegisterUrl = () => {
  return `http://localhost:5555/auth/register`;
};

export const authControllerRegister = async (
  options?: RequestInit,
): Promise<authControllerRegisterResponse> => {
  const res = await fetch(getAuthControllerRegisterUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authControllerRegisterResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as authControllerRegisterResponse;
};

export type authControllerLoginResponse201 = {
  data: void;
  status: 201;
};

export type authControllerLoginResponseSuccess =
  authControllerLoginResponse201 & {
    headers: Headers;
  };
export type authControllerLoginResponse = authControllerLoginResponseSuccess;

export const getAuthControllerLoginUrl = () => {
  return `http://localhost:5555/auth/login`;
};

export const authControllerLogin = async (
  options?: RequestInit,
): Promise<authControllerLoginResponse> => {
  const res = await fetch(getAuthControllerLoginUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authControllerLoginResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as authControllerLoginResponse;
};
