/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Todos example
 * The TODO API description
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';




  export const getAuth = () => {
const authControllerRegister = <TData = AxiosResponse<null>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5555/auth/register`,undefined,options
    ).then((res) => {if (res.data === "") res.data = null; return res as TData;});
  }
const authControllerLogin = <TData = AxiosResponse<null>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5555/auth/login`,undefined,options
    ).then((res) => {if (res.data === "") res.data = null; return res as TData;});
  }
return {authControllerRegister,authControllerLogin}};
export type AuthControllerRegisterResult = AxiosResponse<null>
export type AuthControllerLoginResult = AxiosResponse<null>
