/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Todos example
 * The TODO API description
 * OpenAPI spec version: 1.0
 */
import type { Product } from "./product";

export interface AllProducts {
  data: Product[];
  totalCount: number;
  skip: number;
  take: number;
}
