/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Todos example
 * The TODO API description
 * OpenAPI spec version: 1.0
 */

export interface Product {
  id: number;
  title: string;
  description: string;
  image: string;
  availableQuantity: number;
}
