/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Todos example
 * The TODO API description
 * OpenAPI spec version: 1.0
 */

export type ProductControllerFindAllParams = {
  /**
   * Number of items to skip
   */
  skip?: number;
  /**
   * Number of items to take
   */
  take?: number;
};
