/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Todos example
 * The TODO API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateProductDto {
  title?: string;
  description?: string;
  image?: string;
  availableQuantity: number;
}
