/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Todos example
 * The TODO API description
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AllProducts,
  CreateProductDto,
  Product,
  ProductControllerFindAllParams
} from '.././model';




  export const getProduct = () => {
const productControllerFindAll = <TData = AxiosResponse<AllProducts>>(
    params?: ProductControllerFindAllParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5555/product`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const productControllerCreate = <TData = AxiosResponse<Product>>(
    createProductDto: CreateProductDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5555/product`,
      createProductDto,options
    );
  }
const productControllerFindOne = <TData = AxiosResponse<Product>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5555/product/${id}`,options
    );
  }
const productControllerRemove = <TData = AxiosResponse<null>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `http://localhost:5555/product/${id}`,options
    ).then((res) => {if (res.data === "") res.data = null; return res as TData;});
  }
return {productControllerFindAll,productControllerCreate,productControllerFindOne,productControllerRemove}};
export type ProductControllerFindAllResult = AxiosResponse<AllProducts>
export type ProductControllerCreateResult = AxiosResponse<Product>
export type ProductControllerFindOneResult = AxiosResponse<Product>
export type ProductControllerRemoveResult = AxiosResponse<null>
