/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Todos example
 * The TODO API description
 * OpenAPI spec version: 1.0
 */
import type {
  AllProducts,
  CreateProductDto,
  Product,
  ProductControllerFindAllParams,
} from "../model";

export type productControllerFindAllResponse200 = {
  data: AllProducts;
  status: 200;
};

export type productControllerFindAllResponseSuccess =
  productControllerFindAllResponse200 & {
    headers: Headers;
  };
export type productControllerFindAllResponse =
  productControllerFindAllResponseSuccess;

export const getProductControllerFindAllUrl = (
  params?: ProductControllerFindAllParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:5555/product?${stringifiedParams}`
    : `http://localhost:5555/product`;
};

export const productControllerFindAll = async (
  params?: ProductControllerFindAllParams,
  options?: RequestInit,
): Promise<productControllerFindAllResponse> => {
  const res = await fetch(getProductControllerFindAllUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: productControllerFindAllResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as productControllerFindAllResponse;
};

export type productControllerCreateResponse200 = {
  data: Product;
  status: 200;
};

export type productControllerCreateResponseSuccess =
  productControllerCreateResponse200 & {
    headers: Headers;
  };
export type productControllerCreateResponse =
  productControllerCreateResponseSuccess;

export const getProductControllerCreateUrl = () => {
  return `http://localhost:5555/product`;
};

export const productControllerCreate = async (
  createProductDto: CreateProductDto,
  options?: RequestInit,
): Promise<productControllerCreateResponse> => {
  const res = await fetch(getProductControllerCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createProductDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: productControllerCreateResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as productControllerCreateResponse;
};

export type productControllerFindOneResponse200 = {
  data: Product;
  status: 200;
};

export type productControllerFindOneResponseSuccess =
  productControllerFindOneResponse200 & {
    headers: Headers;
  };
export type productControllerFindOneResponse =
  productControllerFindOneResponseSuccess;

export const getProductControllerFindOneUrl = (id: string) => {
  return `http://localhost:5555/product/${id}`;
};

export const productControllerFindOne = async (
  id: string,
  options?: RequestInit,
): Promise<productControllerFindOneResponse> => {
  const res = await fetch(getProductControllerFindOneUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: productControllerFindOneResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as productControllerFindOneResponse;
};

export type productControllerRemoveResponse200 = {
  data: void;
  status: 200;
};

export type productControllerRemoveResponseSuccess =
  productControllerRemoveResponse200 & {
    headers: Headers;
  };
export type productControllerRemoveResponse =
  productControllerRemoveResponseSuccess;

export const getProductControllerRemoveUrl = (id: string) => {
  return `http://localhost:5555/product/${id}`;
};

export const productControllerRemove = async (
  id: string,
  options?: RequestInit,
): Promise<productControllerRemoveResponse> => {
  const res = await fetch(getProductControllerRemoveUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: productControllerRemoveResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as productControllerRemoveResponse;
};
